############# English navigation ##############

# main menu
[[main]]
name = "About"
pageRef = "/"
weight = 1


[[main]]
name = "You Are Enough Quotes"
pageRef = "/career"
weight = 2

[[main]]
name = "Behind the Product"
pageRef = "/contact"
weight = 3

[[main]]
name = "Our Teams"
pageRef = "/author"
weight = 4


# footer menu
[[footer]]
name = "About"
pageRef = "/"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
