############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "The Power of You Are Enough"
pageRef = "/"
weight = 2

[[main]]
name = " Cute & Aesthetic Thrapy"
pageRef = "/cute_aesthetic_thrapy/aura-wallpaper-make-your-chrome-a-self-care-space/"
weight = 3



# footer menu
[[footer]]
name = "About"
pageRef = "/"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
