############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "The Power of You Are Enough"
pageRef = "/"
weight = 2

[[main]]
name = " Cute & Aesthetic Therapy"
pageRef = "/cute_aesthetic_therapy"
weight = 3

# footer menu
[[footer]]
name = "About"
pageRef = "/"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
